import "server-only";

import { GoogleGenAI } from "@google/genai";
import { buildReportPrompt, REPORT_SYSTEM_INSTRUCTION } from "@/lib/ai/reportPrompts";
import {
  buildReportJsonSchema,
  parseStructuredReportOutput,
  ReportValidationError,
  toVcReportContent,
  validateStructuredReportPayload
} from "@/lib/ai/reportSchema";
import type { VcReportContent } from "@/lib/types";
import { AIProviderError, type AIProvider, type ReportGenerationInput } from "./types";

export { OpenAIReportProvider, DEFAULT_OPENAI_MODEL } from "./openai";

export const DEFAULT_GEMINI_MODEL = "gemini-3.5-flash";
const GEMINI_TIMEOUT_MS = 30_000;

type Recommendation = NonNullable<VcReportContent["finalRecommendation"]>;

function scoreFromInput(input: ReportGenerationInput): number {
  const filled = Object.values(input.sections).filter((value) => value.trim().length > 0).length;
  const completionScore = Math.round(input.completionPercentage * 0.45);
  return Math.max(40, Math.min(92, 38 + completionScore + filled));
}

function recommendation(score: number): Recommendation {
  if (score >= 88) return "Strong Candidate";
  if (score >= 78) return "Investor Conversation Ready";
  if (score >= 68) return "Incubator Ready";
  if (score >= 55) return "Needs Validation";
  return "Not Ready";
}

function evidence(input: ReportGenerationInput, keys: string[], missing: string): string {
  for (const key of keys) {
    const value = input.sections[key]?.trim();
    if (value) return value.slice(0, 900);
  }
  return missing;
}

function mockPayload(input: ReportGenerationInput): unknown {
  const score = scoreFromInput(input);
  const finalRecommendation = recommendation(score);
  const common = {
    startupName: input.workspaceName,
    reportType: input.reportType,
    overallScore: score,
    finalRecommendation
  };

  switch (input.reportType) {
    case "Basic SWOT Report":
      return {
        ...common,
        executiveSummary: `Development mock analysis for ${input.workspaceName}. It uses only the selected Idea Workspace and was not generated by OpenAI.`,
        strengths: ["A completed structured founder document is available for review.", "The problem and solution are presented in one evidence packet."],
        weaknesses: ["Quantified evidence should be attached wherever the workspace currently relies on narrative claims."],
        opportunities: ["Use verified opportunities to test the strongest customer and distribution assumptions."],
        threats: ["Unvalidated assumptions may weaken diligence confidence.", "Execution sequencing remains a founder responsibility."],
        validationScore: score,
        priorityActions: ["Add measurable evidence to descriptive claims.", "State the next validation milestone and deadline.", "Separate confirmed facts from assumptions."],
        readinessStatus: finalRecommendation
      };
    case "Premium SWOT Analysis":
      return {
        ...common,
        detailedStrengths: ["The founder has completed a structured Idea Workspace.", "The submission can be compared consistently by reviewers."],
        detailedWeaknesses: ["Claims still need source evidence and measurable success thresholds."],
        marketOpportunities: [evidence(input, ["target_market", "target_users"], "Target-market evidence is missing and should be validated.")],
        executionThreats: ["Milestones without owners or dates may delay validation.", "Unproven distribution assumptions create execution risk."],
        founderReadiness: "Readiness depends on turning the strongest narrative claims into verifiable customer, product, and execution evidence.",
        riskRating: score >= 78 ? "Medium" : "High",
        prioritizedImprovements: ["Attach evidence to traction claims.", "Define the next validation gate.", "Document the largest execution assumption."]
      };
    case "Full Brief Report":
      return {
        ...common,
        executiveSummary: `The selected ${input.template} document is complete and ready for structured review. This development report does not add external facts.`,
        problemClarity: evidence(input, ["problem_statement", "problem", "ai_problem"], "Problem evidence is missing."),
        solutionStrength: evidence(input, ["solution", "product_overview"], "Solution evidence is missing."),
        targetUsers: evidence(input, ["target_users", "target_market", "target_audience"], "Target-user evidence is missing."),
        businessModel: evidence(input, ["business_model", "pricing_model", "commercialization"], "Business-model evidence is missing."),
        marketOpportunity: "Validate the reachable market with founder-supplied, sourced bottom-up assumptions before presenting a number as fact.",
        competitivePosition: evidence(input, ["competitive_advantage", "competitive_landscape"], "Competitive-position evidence is missing."),
        teamReadiness: evidence(input, ["team", "team_members"], "Founder and team evidence is missing."),
        executionRisks: ["Unvalidated assumptions may delay execution.", "Milestone ownership and timing require confirmation."],
        investmentReadiness: `Current structured-readiness score: ${score}/100. Recommendation: ${finalRecommendation}.`,
        recommendations: ["Attach source evidence to the strongest claims.", "Define the next risk-reducing milestone."]
      };
    case "Bottleneck Report":
      return {
        ...common,
        criticalBlockers: ["Convert unsupported claims into evidence.", "Choose one measurable validation milestone."],
        productBottlenecks: ["Define the smallest product proof that reduces the highest risk."],
        marketBottlenecks: ["Validate buyer, user, urgency, and acquisition path separately."],
        teamBottlenecks: ["Assign ownership for product, customer validation, and distribution."],
        executionBottlenecks: ["Sequence work by risk reduction rather than feature volume."],
        revenueBottlenecks: ["Test willingness to pay before treating pricing assumptions as evidence."],
        priorityFixes: ["Document missing proof.", "Run the highest-value validation test.", "Update the workspace with results before regenerating."]
      };
    case "Competitor Defensive Report":
      return {
        ...common,
        competitorLandscape: [evidence(input, ["competitive_landscape", "competitive_advantage"], "Competitor evidence is missing; map direct, indirect, and incumbent alternatives.")],
        differentiation: ["Express the founder-supplied differentiation as a testable customer outcome."],
        moatStrength: "No durable moat should be claimed until proprietary advantage, distribution, switching cost, or execution evidence is documented.",
        copyRisk: ["Feature copying by incumbents.", "Distribution capture by a better-funded alternative."],
        distributionAdvantage: "Distribution advantage is unconfirmed unless the workspace includes repeatable channel evidence.",
        defensibilityScore: Math.max(35, score - 8),
        strategicRecommendations: ["Name the top alternatives.", "Prove why customers switch.", "Document a defensibility milestone."]
      };
    case "Roadmap Report":
      return {
        ...common,
        next30Days: ["Close the largest evidence gap.", "Run customer validation interviews.", "Update the Idea Workspace with results."],
        next90Days: ["Complete the first measurable product or pilot milestone.", "Test willingness to pay.", "Review the acquisition hypothesis."],
        sixMonthPlan: ["Reach a repeatable validation signal before expanding scope.", "Prepare an evidence-backed diligence packet."],
        productMilestones: ["Define an MVP outcome tied to user behavior, not feature count."],
        validationMilestones: ["Record interview, pilot, or experiment evidence in the workspace."],
        tractionMilestones: ["Choose a traction metric only after its source and definition are documented."],
        revenueMilestones: ["Validate pricing and payment intent before forecasting revenue."],
        fundraisingMilestones: ["Begin investor conversations after the next material risk is reduced."]
      };
    case "Investor Scorecard Report":
      return {
        ...common,
        investorReadinessScore: score,
        marketPotentialScore: Math.max(35, score - 2),
        productClarityScore: Math.min(100, score + 3),
        businessModelScore: Math.max(35, score - 4),
        teamScore: Math.max(35, score - 3),
        tractionScore: Math.max(30, score - 8),
        riskScore: Math.min(100, 100 - score + 20)
      };
  }
}

export class MockProvider implements AIProvider {
  readonly name = "mock" as const;
  readonly model = "deterministic-development-mock";

  async generateReport(input: ReportGenerationInput) {
    const payload = validateStructuredReportPayload(mockPayload(input), input.reportType);
    return toVcReportContent(payload);
  }
}

export class GeminiProvider implements AIProvider {
  readonly name = "gemini" as const;
  readonly model: string;
  private readonly ai: GoogleGenAI;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY?.trim();
    if (!apiKey) throw new AIProviderError("NOT_CONFIGURED", "Gemini is not configured on the server.");
    this.model = process.env.GEMINI_MODEL?.trim() || DEFAULT_GEMINI_MODEL;
    this.ai = new GoogleGenAI({ apiKey });
  }

  async generateReport(input: ReportGenerationInput) {
    try {
      const response = await this.ai.models.generateContent({
        model: this.model,
        contents: buildReportPrompt(input),
        config: {
          systemInstruction: REPORT_SYSTEM_INSTRUCTION,
          temperature: 0.2,
          maxOutputTokens: 8192,
          responseMimeType: "application/json",
          responseJsonSchema: buildReportJsonSchema(input.reportType),
          httpOptions: { timeout: GEMINI_TIMEOUT_MS }
        }
      });

      const text = response.text?.trim();
      if (!text) throw new AIProviderError("REFUSAL", "Gemini did not return report content.");
      const payload = parseStructuredReportOutput(text, input.reportType);
      return toVcReportContent(payload);
    } catch (error) {
      if (error instanceof AIProviderError) throw error;
      if (error instanceof ReportValidationError) {
        throw new AIProviderError("INVALID_OUTPUT", "Gemini returned an invalid structured report.");
      }

      const details = error instanceof Error ? error.message.toLowerCase() : "";
      if (details.includes("timeout") || details.includes("timed out") || details.includes("abort")) {
        throw new AIProviderError("TIMEOUT", "Gemini report generation timed out.");
      }
      if (details.includes("429") || details.includes("quota") || details.includes("resource_exhausted")) {
        throw new AIProviderError("QUOTA", "Gemini report generation is temporarily rate limited.");
      }
      throw new AIProviderError("PROVIDER_ERROR", "Gemini report generation failed.");
    }
  }
}
